version: '3.3'

services:
  logspout:
    image: gliderlabs/logspout:v3
    command: 'udp://logstash:12201'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    deploy:
      placement:
        constraints: [node.role == worker]

  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS="-Xmx256m -Xms256m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [node.role == worker]

  kibana:
    image: kibana:7.9.3
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    deploy:
      placement:
        constraints: [node.role == worker]

  logstash:
    image: logstash:7.9.3
    ports:
      - "12201:12201/udp"
    depends_on:
      - elasticsearch
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]
    volumes:
      - logstash-pipeline:/usr/share/logstash/pipeline/

volumes:
  esdata:
    driver: local
  logstash-pipeline:
    driver: local

# services:
#   logstash:
#     image: logstash:2.1.1
#     environment:
#       - STDOUT=true
#     links:
#       - elasticsearch
#     depends_on:
#       - elasticsearch
#       - kibana
#     command: 'logstash -e "input { udp { port => 5000 } } output { elasticsearch { hosts => elasticsearch } }"'
#   kibana:
#     image: kibana:4.1.2
#     links:
#       - elasticsearch
#     environment:
#       - ELASTICSEARCH_URL=http://elasticsearch:9200
#     ports:
#       - '5601:5601'
#     depends_on:
#       - elasticsearch
#   elasticsearch:
#     image: elasticsearch:1.5.2
#     ports:
#       - '9200:9200'
#       - '9300:9300'

