version: "3.7"
services:
  web:
    image: nginx
    labels:
      - "traefik.http.routers.whoami.rule=Host(`my_nginx.sys.example.com`)"
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=my_nginx.sys.example.com
     - NGINX_PORT=80

networks:
  default:
    external: true
    name: traefik-public
